remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-redirect-from
title: Erfan Ahmadi
description: Sharing my journey and experience in Graphics, Rendering and GPU Programming
kramdown:
    syntax_highlighter_opts:
       disable : true
