theme: jekyll-theme-cayman
title: Graphics Coder
markdown: CommonMarkGhPages
CommonMarkGhPages:
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
#markdown: CommonMarkGhPages
#CommonMarkGhPages:
#  syntax_highlighter: rouge
