theme: jekyll-theme-dinky
title: Graphics Coder
plugins:
  - jekyll-redirect-from
markdown: CommonMarkGhPages
CommonMarkGhPages:
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
#markdown: CommonMarkGhPages
#CommonMarkGhPages:
#  syntax_highlighter: rouge
